---
# vars file for default_vars
forward_dns_zone: sarat.internal
reverse_dns_zone: 0.0.10.in-addr.arpa
support_server_ip: 10.0.0.1
support_server_fqdn: support.sarat.internal
support_server_short_name: support
public_dns_ip: 8.8.8.8
internal_ip_subnet: 10.0.0.0/24
toplevel_domain: sarat.internal
last_octet_support_ip: 1
cluster_basedomain: sarat.internal
cluster_name: test-cluster
rhcos_mirror: https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.5/4.5.6/
installer_initramfs_file: rhcos-installer-initramfs.x86_64.img
installer_kernel_file: rhcos-installer-kernel-x86_64
installer_image_file: rhcos-metal.x86_64.raw.gz
gateway_ip: 10.0.0.1
oc_files_url: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest-4.5/
oc_client_url: openshift-client-linux.tar.gz
oc_install_file: openshift-install-linux.tar.gz
dhcp_subnet: 10.0.0.0
dhcp_start_ip: 10.0.0.1
dhcp_end_ip: 10.0.0.252
dhcp_netmask: 255.255.255.0
dhcp_broadcast_address: 10.0.0.255
artifact_dir: /home/ansible
core_ssh_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDK/rQz/Clatq6e29IRNzmTqZRoqvE3jrDt5oouwfYnjqW+pQ8QD0fGGzC207oYTvUi5J62k1rfYCIlADxU/yzAMO06rixh4XBZd49vDBoHR9nQYQyHSZ9vetRYhbZWsxnsYrbsQNYtJ7JLM4+xeROUZgkR0IvWw4njzP0WKueB/TcgvZJJPtl0XuqspEtIEJU3M6Q0IT8plX4DZCvZrnkf39DtkE2DauZ+H3SNMYXODEOK4nJNCAVd1dc9s5g0k8VejYQ+YuSVtXv5AxAK/TX7xU/Bs7M2CmpIfCOMMHu+sehD/Z2Kvxhohky6m/dJ041k/OeXhgId1APgEMPH7H8T ansible@supportserver

# These variables below are for disconnected installs where the support server is also a docker registry
CSR_country_name: US
CSR_organization_name: Sarat Yadavalli
CSR_email_address: srinivas.sarat.yadavalli@ibm.com
CSR_state: GA
CSR_locality: Atlanta
CSR_organizational_unit_name: None
local_docker_registry_url: docker-registry.{{ forward_dns_zone }}
ocp_release: 4.5.6-x86_64         
local_registry: '{{ local_docker_registry_url }}:5000'       
local_repository: 'ocp4/openshift4'      
product_repo: 'openshift-release-dev'      
local_secret_json_filename: 'pull-secret.json'      
release_name: 'ocp-release'
